### ISSUE TITLE
MAJ logos équipes

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4rugby#12]
Uruguay
Tonga
Argentine

**Comment by johanpoirier** [comment]
Je vais utiliser directement les logos du site http://www.rugbyworldcup.com/

**Comment by glideblue7** [comment]
Donc les drapeaux des pays et non les blasons des fédérations de rugby ?

**Comment by johanpoirier** [comment]
Oui, tu préférais les autres logos ?

Ca m'arrangeait surtout techniquement car j'ai repris leur boulot (tous les logos sont sur une seule image et ça améliore la rapidité d'affichage du site).

**Comment by glideblue7** [comment]
oui oui pas de souci, fais le plus pratique pour toi

c'était une simple question, tout m'ira parfaitement
