### ISSUE TITLE
Classements des poules dans l'onglet Mes pronostics

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4rugby#20]
Basés sur les pronostics et non sur les résultats réels (comme dans l'onglet Résultats) : donc potentiellement différents et qui occasionnent des interrogations de nombreux pronostiqueurs. Et peuvent influer sur les pronostics des joueurs non avertis ... Le change-t-on ?

**Comment by johanpoirier** [comment]
Le changer non, mais peut-être changer le libellé ?
