### ISSUE TITLE
Petit bug d'affichage "super score"

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4rugby#21]
Sur le site Abmi, pour le match Samoa - Etats-Unis, il est indiqué 3 super scores, et quand on clique dessus, 2 noms seulement apparaissent

**Comment by johanpoirier** [comment]
Il s'agissait des pronos d'un utilisateur qui a été supprimé. J'ai nettoyé la table où il y avait un autre fantôme.
