### ISSUE TITLE
Match nul en 1/4 de finale?

### ISSUE THREAD

**Issue by flanker1** [johanpoirier/bet4rugby#29]
Quelques personnes me demandent comment indiquer l'équipe vainqueur s'ils pronostiquent un match nul en 1/4 de finale....

**Comment by johanpoirier** [comment]
Oui je travaille dessus.

**Comment by johanpoirier** [comment]
Ca devrait être mieux là, non ?

**Comment by flanker1** [comment]
Perfect!!

2015-10-12 10:07 GMT+02:00 Johan Poirier notifications@github.com:
