### ISSUE TITLE
E-mail

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4rugby#32]
Modifier l'adresse mail lorsqu'un utilisateur clique sur e-mail en bas de page : 

johan.poirier+cdm2019@gmail.com pour le site global

sylvain.poirier+cdm2019@gmail.com pour le site ABMI

**Comment by johanpoirier** [comment]
En fait, les adresses email étaient bonnes dans la config du site mais pas utilisées dans les templates. Voilà ce qu'il y a du coup :

- johan.poirier+rwc2019@gmail.com pour le site global
- sylvain.poirier+rwc2019@gmail.com pour le site ABMI
